### ISSUE TITLE
Half of the Leaderboard Not being seen.

### ISSUE THREAD

**Issue by ToastyCoffeeYum** [DankMemer/dankmemer.lol#112]
So, today in our server when one of my friends opened the leaderboard, only three of the member's stats were shown. We did it again after some time and this time there were only 4 of the stats shown. We decided to wait a little and if it still didn't do anything, we will report this bug. This first happened at 19:53 PM (IST) and it is 20:17 PM (IST) While I'm writing this. 

Please look into it, Thank you.

**Comment by melmsie** [comment]
no
