### ISSUE TITLE
Abnormal behaviour during Reee!

### ISSUE THREAD

**Issue by Wise2006** [DankMemer/dankmemer.lol#14]
**Describe the bug**
When the number of loot boxes is lesser than 1 or greater than 99, there is a ree.
But the ree abnormally takes the bottom of the page and sticks it to the top.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Lootboxes'.
2. Scroll down to the bottom.
3. Click the minus button.
4. See error.

**Expected behaviour**
Either the page scrolls back to the top before the ree or the bottom bar stays in its place.

**Screenshots**
![dank](https://user-images.githubusercontent.com/45759535/80091284-7562bc80-857e-11ea-8f01-764baeb3d250.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome, Microsoft Edge
 - Version: 81.0.4044.113 (Official Build) (64-bit) [Chrome],
 - Version: 81.0.416.62 (Official build) (64-bit) [Edge] 

**Additional context**
Hope you fix this soon! Thanks, Mel (@melmsie ), Aetheryx and team!
Reeeee!
<3

**Comment by Wise2006** [comment]
Should I move this to 
[https://github.com/DankMemer/dank-memer-suggestions-and-bugs](url) ?

**Comment by Aoof** [comment]
That is because the animation is applied to the body tag. 

So a probable fix would be to change the animation tag to `.content.loot` tag, or wrap up `.navbar` and `.content.loot` together into 1 tag, I still haven't seen the source code of the web-page (if there's any, I'll go search for it and give an exact fix to the problem)

**Comment by DaChickenKing** [comment]
> Should I move this to [the bug report repository](https://github.com/DankMemer/dank-memer-suggestions-and-bugs) ?

Probably, yes.

**Comment by Wise2006** [comment]
> > Should I move this to [the bug report repository](https://github.com/DankMemer/dank-memer-suggestions-and-bugs) ?
> 
> Probably, yes.

Done!
