### ISSUE TITLE
Revamping the "help" System

### ISSUE THREAD

**Issue by Matthew0909** [DankMemer/dankmemer.lol#18]
So if I put "pls help hunt," it tells me how to use it, the aliases, and cooldowns. But if I go to the _dank memer channel_ and do ".hunt" it gives me the following information: 

Hunting
— Hunting is our newest addition in the currency system!
— You need a Hunting Rifle to hunt pls buy rifle.
— After which you will be able to hunt by doing pls hunt.

Outcomes
Animals: :skunk: Skunk, :rabbit2: Rabbit, :petduck: Duck, :deer: Deer, :boar: Boar.

Beat the Boss event
Reward: :dragon_face: Dragon
Punishments: On failing, you will either Die or lose your Hunting Rifle.

Notes:
— Boss Event is the only way to obtain the Dragon.

You should make the information that comes with ".hunt" what actually comes up when you type in "pls help hunt," along with the cooldowns. It would make it a lot easier to learn the bot and learn about new commands and see how to use them.

**Comment by melmsie** [comment]
I don't want the bot hand holding every user, I want them discovering things on their own. I don't honestly care for the mods doing this for everyone, so consider that an extra perk of being active in the community, seeing more detailed help.

**Comment by melmsie** [comment]
Also, this is NOT the repo to post bot suggestions on. This is for the website.

https://github.com/DankMemer/dank-memer-suggestions-and-bugs/issues
