### ISSUE TITLE
Keep getting failed work attempts when not working

### ISSUE THREAD

**Issue by carmstrong070** [DankMemer/dankmemer.lol#21]
**Describe the bug**
After starting a new job, I will get numerous failed work attempts while not using the `pls work` command

**To Reproduce**

**Expected behavior**
Failed work attempts only occur when you fail the work task after using the `pls work` command

**Screenshots**
![Screenshot of issue](https://cdn.discordapp.com/attachments/609151771478065156/726226087889207306/unknown.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - OS: Windows 10 64-Bit (10.0.18362)
 - Discord

**Additional context**
You can see from the screenshot that I have only had the job for 5 hours so I could only have worked 5 times (4 pass 1 fail). However, I have 8 work attempts logged (4 pass 4 fail).

**Comment by melmsie** [comment]
this is not a repo for dank memer bot stuff
