### ISSUE TITLE
Use Link for internal URLs

### ISSUE THREAD

**Issue by MMDF** [DankMemer/dankmemer.lol#22]
https://github.com/DankMemer/dankmemer.lol/blob/24a4c61e90dfa8118a4dce127a8043415b66d59c/src/app/Pages/Landing/index.jsx#L28

Some of the rendered links are internal and using an `a` tag causes a reload. What about switching to using something like this:

>Note, you could make your own Link that does the check and then renders an `<a/>` or a `<Link/>`
>
>``` js
>var YourLink = React.createClass({
> render () {
>   return this.isExternal() ? <a/> : <Link/>
> }
>});
>```

_Originally posted by @ryanflorence in https://github.com/ReactTraining/react-router/issues/1147#issuecomment-113180884_

**Comment by InBlue** [comment]
Closing this as it has likely been fixed during the redesign.
