### ISSUE TITLE
Balance and inventory bug (gone from the account)

### ISSUE THREAD

**Issue by Harfanse** [DankMemer/dankmemer.lol#34]
**Describe the bug**
Is this some kind of bug or what? I was hunting with my rifle at 12.37AM at my country and then 10 minutes later it was gone from my inventory and i didnt use the command "pls hunt" inbetween the 10 minute gap.
Same goes to my balance, i was checking my balance yesterday 9.20pm at my country. It was still there and then today i checked after doing some command that im sure doesn't decrease my balance but some of money are gone from my balance, after i saw that i checked every server that i joined that has dank memer in it if someone robbed me, i even checked with my user id too just to make sure and no one robbed or stole my money. 

**To Reproduce**
"I dont know it just happened"

**Expected behavior**

**Screenshots**
![Screenshot_20200906-005012_Discord](https://user-images.githubusercontent.com/70817398/92311094-32a9fa00-efde-11ea-9085-1f20b677b419.jpg)
![Screenshot_20200906-005027_Discord](https://user-images.githubusercontent.com/70817398/92311095-33db2700-efde-11ea-8027-e63009f2be5c.jpg)
![Screenshot_20200906-005048_Discord](https://user-images.githubusercontent.com/70817398/92311096-3473bd80-efde-11ea-92c4-c6b3710b01bf.jpg)
![Screenshot_20200906-005122_Discord](https://user-images.githubusercontent.com/70817398/92311097-350c5400-efde-11ea-8645-309690bc2609.jpg)

**Smartphone (please complete the following information):**
 - Device: [Samsung A30]
 - OS: [Android 10]
 - Browser [Discord App]
 - Version [37.1]

**Additional context**
I lost some of my balance and my hunting rifle PERMANENTLY

**Comment by melmsie** [comment]
does this look like dank memer bug reports?
