### ISSUE TITLE
Can there be a frequently asked questions board in the support server?

### ISSUE THREAD

**Issue by Baelorwolf** [DankMemer/dankmemer.lol#35]
Not necessarily a problem in not having one I just feel having one can really improve the support.

I was thinking something like for example
Q. "Why won't inventory 2 [user] work?"
A. Because the command for it is "Inventory [user] 2"
I feel with something like this it could save the staff some time instead of constantly being asked the same question over and over again.

I feel an alternative to this is making pins in the support channels of questions and answers to frequently asked questions. (Although with my time of running servers I've noticed people don't look at pins -_-) but I did notice there were already pins there that some were not for support questions so I felt that would be better as an alternative.

**Comment by melmsie** [comment]
once again, this is NOT an issue board for the bot, the support server, or anything else like that.
