### ISSUE TITLE
Can't redo quests that have already been completed

### ISSUE THREAD

**Issue by ItzButterBall** [DankMemer/dankmemer.lol#36]
**Describe the bug**
When trying to redo a quest that DOESN'T say non-repeatable, it keeps saying this message: "You've already completed this quest! You gotta wait **0 seconds** until you can do it again lol". 

**To Reproduce**
1. Go to the quest list
2. Complete the 'Chronic Gambler' quest or some other non-repeatable quest
3. Wait for the time limit for each quest to finish

**Expected behavior**
Because it is non-repeatable, I expected that it would have let me do the quest again.

**Screenshots**
![image](https://user-images.githubusercontent.com/70670513/92738579-eb4ea100-f330-11ea-95fd-52a2b2d2b741.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version 85.0.4183.102

**Smartphone (please complete the following information):**

**Additional context**
Some other people have had this bug before as well, but I don't know if it was ever reported.

**Comment by melmsie** [comment]
this is NOT a repo for dank memer
