### ISSUE TITLE
Favicon doesn't render

### ISSUE THREAD

**Issue by GamesProSeif** [DankMemer/dankmemer.lol#4]
**Describe the bug**
A favicon doesn't render when you open any page

**To Reproduce**
1. Host the server
2. Open any page

**Expected behavior**
The page should render the favicon, but doesn't

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win32
 - Browser chrome
 - Version 1.0.0

**Smartphone (please complete the following information):**
 - Device: Samsumg Note 8
 - OS: Android 9
 - Browser chrome
 - Version 1.0.0

**Additional context**
I have tried working on the problem myself, but I'm not that experienced and couldn't figure out what was going on.

The problem basically is:  
In the `head` tag, you refer to a `link` to get the icon, its `href` attribute is `https://dankmemer.lol/96fe07365c03726ce2b25e4988146aee.png`. That page doesn't return a png, instead, it returns an HTML rendered file. In order to solve this problem, make a static routed folder that can include a link to that image (probably `src\app\assets\memer.png`), and it will be solved.

I wanted to work on this, but as I said, I didn't understand most of what was there, and I didn't want to change the HTTP methods you use to render stuff.

**Comment by Devoxin** [comment]
Most browsers by default also look for a file called "favicon.ico" so converting and renaming should work too

**Comment by aetheryx** [comment]
https://dankmemer.lol/assets/memer.png is already served on it's own, the href attribute just need updated

**Comment by aetheryx** [comment]
fix landed in https://github.com/DankMemer/dankmemer.lol/commit/fdbfe0c615fda777d6208f61c13b4bfc56ceab0f
