### ISSUE TITLE
Query about the dank memer bot (Discord)

### ISSUE THREAD

**Issue by mudit67** [DankMemer/dankmemer.lol#45]
Hey @aetheryx,
I am a beginner developer and am trying to make a discord bot of my own.
but my bot is unable to communicate with your bot.
for example, if my bot sends a command like "pls help", DankMemer just ignores it.

can you please help me with this?

thank you.

**Comment by aetheryx** [comment]
this repository is not for questions about the bot itself
like most bots, dank memer intentionally ignores other bots because you could bot currency without breaking discord terms of service otherwise
