### ISSUE TITLE
Add Database model

### ISSUE THREAD

**Issue by toddhow** [DankMemer/dankmemer.lol#68]
Since there is no database model currently adding on to parts that use the database requires you to recreate the database.

**Comment by toddhow** [comment]
> we use MongoDB; writing schema's is optional. you don't need to recreate anything

Oh, I confused a error about there being no keys.json file. Do you know where the template for that is then?

**Comment by melmsie** [comment]
https://github.com/DankMemer/dankmemer.lol/blob/master/keys.example.json
