### ISSUE TITLE
Can't Login on Website using my hosted version

### ISSUE THREAD

**Issue by phineapuuu** [DankMemer/dankmemer.lol#70]
**Describe the bug**
Can't Login on Website using my hosted version

**Desktop (please complete the following information):**

 - Browser: Chrome
 - Version Windows 7

**Additional context**

**Screenshots**
I'm trying to host a version of my website (For Personal Use) and i can't login discord cause it says Invalid OAuth2.  In the Developer OAuth2 i put this http://localhost:8080/api/callback and i also replaced the oauth/callback in the code and replaced it with that, i tried to changed it several time but same result. How do i fix it?

![image](https://user-images.githubusercontent.com/75511393/114289681-7c931b00-9aac-11eb-88b6-0aeae92b3258.png)

**Comment by InBlue** [comment]
We don't provide support for this repo.

**Comment by phineapuuu** [comment]
but how to fix

**Comment by melmsie** [comment]
"We don't provide support for this repo." means we don't provide support for this repo.
