### ISSUE TITLE
Mobile site only shows logout, even if not logged in

### ISSUE THREAD

**Issue by biscotit** [DankMemer/dankmemer.lol#72]
When accessing the website on a mobile device, in which it's small enough for the menu to appear instead of the tabs at the top, it will show a button 'Logout', even if a user is not logged in.

**To Reproduce**
1. Go to https://dankmemer.lol/ on a mobile device
2. Click on ≡ in the top right
3. Scroll down to 'Logout'

**Expected behavior**
A login button

**Screenshots**
https://cdn.discordapp.com/attachments/715380919610900540/831781736219410442/image0.png
https://cdn.discordapp.com/attachments/715380919610900540/831780032216301568/video0.mp4

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14.4.2
 - Browser: Safari and Chrome

![image0](https://user-images.githubusercontent.com/32405102/114665973-065b1680-9d41-11eb-8313-fd16636bd826.png)

https://user-images.githubusercontent.com/32405102/114665923-f5aaa080-9d40-11eb-886c-a9dbe2c44bb0.mp4

**Comment by InBlue** [comment]
Thank you for that! This will be fixed shortly, along side other minor issues with this release.
