### ISSUE TITLE
no

### ISSUE THREAD

**Issue by Loroxxie** [DankMemer/dankmemer.lol#88]
I think there should be a few ways to be able to get your pet back if it has ran away. Its a lot easier to lose your pet now as I had went 1 day without caring for it, and it ran away. 

If it has ran away, maybe there could be commands such as to put up "posters" or ask people if they have or have seen your pet. 

of course, you should care for your pet if you don't want to it run away, but its very possible you could forget or something may not allow you to get on to use dank memer that day to care for it. So yeah

**Comment by Codeize** [comment]
This isn't a repo for the bot..
