### ISSUE TITLE
Crypt utility seems outdated

### ISSUE THREAD

**Issue by didinele** [DankMemer/dankmemer.lol#9]
Running the crypt function will always throw `Error: Invalid IV length`. I have tried a lot of lengths & string for the IV string, and after reading up on it a little it's pretty safe to assume this is happening on any node version above 6.

So this also made me wonder what version you guys deploy this on.

I have also tested this on Node 13.2.0

What I read up on:
- https://github.com/nodejs/node/issues/6696
- https://stackoverflow.com/questions/42485408/getting-error-of-invalid-iv-length-while-using-aes-256-cbc-for-encryption-in-nod

**Comment by aetheryx** [comment]
config.cryptKeys has to be an array of a 16-byte and a 32-byte base64 string

**Comment by didinele** [comment]
So that's how you set them in the config file? Huh, let me try.

**Comment by didinele** [comment]
Yup! Thanks a lot, that worked. You guys should consider an example config file :p

**Comment by aetheryx** [comment]
this repo isn't open sourced for selfhostability, it's open source for transparency and educational purposes

**Comment by didinele** [comment]
What I was using it for in the first place, wanted to see how you guys did OAuth flow but I needed encryption either way, so I took a little peek at the crypt file.

Anyway, thanks a lot for the help!

**Comment by AkgunFatih** [comment]
> Yup! Thanks a lot, that worked. You guys should consider an example config file :p

can you help me how you fixed it
i don't need the bot, this is for educational only

**Comment by kablekompany** [comment]
> > Yup! Thanks a lot, that worked. You guys should consider an example config file :p
> 
> can you help me how you fixed it
> i don't need the bot, this is for educational only

This isn't for the bot anyway. This is the website.

**Comment by AkgunFatih** [comment]
> > > Yup! Thanks a lot, that worked. You guys should consider an example config file :p
> > 
> > 
> > can you help me how you fixed it
> > i don't need the bot, this is for educational only
> 
> This isn't for the bot anyway. This is the website.

i know, i am trying to learn express js with this oauth
